version: '3'
services:
  api:
    build: .
    command: rspec
    ports:
      - 3000:3000
      - 80:80
    command: bash -c "rails s --binding 0.0.0.0 --port 80"
    volumes:
      - '.:/usr/src/app'
    environment:
      DATABASE_URL: postgres://postgres:h1mamapa55db@db/timeclock_production
      DATABASE_URL_DEV: postgres://postgres:h1mamapa55db@db/timeclock_development
      DATABASE_URL_TEST: postgres://postgres:h1mamapa55db@db/timeclock_test
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: 'true'
    depends_on: 
      - db
  
  db:
    image: postgres:12
    ports:
        - 5432:5432
    volumes:
      - ./tmp/db:/var/lib/postgres/data
    environment:
      POSTGRES_PASSWORD: h1mamapa55db
  
  # adminer:
  #   image: adminer
  #   ports:
  #     - 8080:8080

